
desc "Process Staging build"
lane :process_build do |options|
  update_dependencies(
    git_branch: options[:branch]
  )
  gradle(
    task: 'assemble',
    flavor: options[:flavor],
    build_type: options[:build_type],
    project_dir: '../../../../android'
  )
  if options[:installr]
    file = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    upload_installr(
      file: file,
      notes: options[:notes] || "Fastlane build"
    )
  end
end
