before_all do
  Dotenv.overload '.env'

  bundle_install
end

ios_project_path = "../../../../ios"
xcodeproj = "#{ios_project_path}/edular.xcodeproj"

desc 'Process build'
lane :process_build do |options| 
  update_dependencies(
    git_branch: options[:branch],
  )
  cocoapods(
    podfile: "#{ios_project_path}/Podfile", 
    use_bundle_exec: true,
    try_repo_update_on_error: true,
  )
  update_project_team( # Set the right team on your project
    path: xcodeproj,
    teamid: ENV['APPLE_TEAM_ID'],
    targets: ["anu", "AnuNotificationServiceExtension"]
  )
  update_project_provisioning(
    xcodeproj: xcodeproj,
    profile: options[:profile],
    target_filter: "anu", # matches name or type of a target
    build_configuration: "Release",
  )
  update_project_provisioning(
    xcodeproj: xcodeproj,
    profile: options[:profile_notification],
    target_filter: "AnuNotificationServiceExtension",
    build_configuration: "Release",
  )
  build_app(
    workspace: "#{ios_project_path}/edular.xcworkspace",
    clean: true,
    scheme: options[:scheme],
    export_method: options[:export_method],
    output_name: options[:output_name],
    # export_options: {
    #   provisioningProfiles: {
    #     "#{ENV['APP_IDENTIFIER']}.staging" => ENV["sigh_#{ENV['APP_IDENTIFIER']}.staging_adhoc_profile-name"],
    #     "#{ENV['APP_IDENTIFIER']}.staging.AnuNotificationServiceExtension" => ENV["sigh_#{ENV['APP_IDENTIFIER']}.staging.AnuNotificationServiceExtension_adhoc_profile-name"],
    #     "#{ENV['APP_IDENTIFIER']}" => ENV["sigh_#{ENV['APP_IDENTIFIER']}_adhoc_profile-name"],
    #     "#{ENV['APP_IDENTIFIER']}.AnuNotificationServiceExtension" => ENV["sigh_#{ENV['APP_IDENTIFIER']}.AnuNotificationServiceExtension_adhoc_profile-name"]
    #   }
    # },
    include_symbols: true,
    include_bitcode: true,
    skip_profile_detection: true,
    build_path: "./builds",
    output_directory: "./builds"
  )
  if options[:installr]
    file = Actions.lane_context[SharedValues::IPA_OUTPUT_PATH]
    upload_installr(
      file: file,
      notes: options[:scheme]
    )
  end
end

desc "Process staging build"
lane :process_staging_build do |options|
  match(
    app_identifier: ["#{ENV['APP_IDENTIFIER']}.staging", "#{ENV['APP_IDENTIFIER']}.staging.AnuNotificationServiceExtension"],
    type: 'adhoc',
    username: ENV['APPLE_ID'],
    team_id: ENV['APPLE_TEAM_ID'],
    git_branch: ENV['CLIENT'],
    force_for_new_devices: true,
  )
  process_build(
    branch: options[:branch],
    installr: options[:installr],
    scheme: "#{ENV['CLIENT']} staging",
    output_name: ENV['STAGING_NAME'],
    export_method: "ad-hoc",
    profile: ENV["sigh_#{ENV['APP_IDENTIFIER']}.staging_adhoc_profile-path"],
    profile_notification: ENV["sigh_#{ENV['APP_IDENTIFIER']}.staging.AnuNotificationServiceExtension_adhoc_profile-path"]
  )
  sync_git(
    message: "chore: staging build"
  )
end

desc "Process adhoc build"
lane :process_adhoc_build do |options|
  match(
    app_identifier: [ENV['APP_IDENTIFIER'], "#{ENV['APP_IDENTIFIER']}.AnuNotificationServiceExtension"],
    type: 'adhoc',
    username: ENV['APPLE_ID'],
    team_id: ENV['APPLE_TEAM_ID'],
    git_branch: ENV['CLIENT'],
    force_for_new_devices: true,
  )
  process_build(
    branch: options[:branch],
    installr: options[:installr],
    scheme: "#{ENV['CLIENT']} prod",
    output_name: ENV['PROD_NAME'],
    export_method: "ad-hoc",
    profile: ENV["sigh_#{ENV['APP_IDENTIFIER']}_adhoc_profile-path"],
    profile_notification: ENV["sigh_#{ENV['APP_IDENTIFIER']}.AnuNotificationServiceExtension_adhoc_profile-path"]
  )
  sync_git(
    message: "chore: adhoc build"
  )
end

desc "Process prod build"
lane :process_prod_build do |options|
  build_number = options[:build_number]
  puts options
  if build_number.nil?
    UI.message "Don't specify build number. Getting latest build number from testflight"
    latest_build = 0
    begin
      latest_build = latest_testflight_build_number(
        username: ENV['APPLE_ID'],
        # team_id: "119976767", #ENV['APPLE_TEAM_ID'],
        app_identifier: ENV['APP_IDENTIFIER']
      )
    rescue => ex
      UI.error "latest_testflight_build_number got error #{ex}. Trying to get build number from plist"
      latest_build = get_build_number_from_plist(
        xcodeproj: xcodeproj,
        target: 'anu',
      ).to_i
      UI.message "Build number in plist: #{latest_build}"
    end
    build_number = latest_build + 1
  end
  increment_version_number_in_plist(
    xcodeproj: xcodeproj,
    version_number: options[:version_number], # Set a specific version number
    target: 'anu'
  )
  increment_version_number_in_plist(
    xcodeproj: xcodeproj,
    version_number: options[:version_number], # Set a specific version number
    target: 'AnuNotificationServiceExtension'
  )
  increment_build_number_in_plist(
    xcodeproj: xcodeproj,
    build_number: build_number.to_s,
    target: 'anu'
  )
  increment_build_number_in_plist(
    xcodeproj: xcodeproj,
    build_number: build_number.to_s,
    target: 'AnuNotificationServiceExtension'
  )
  match(
    app_identifier: [ENV['APP_IDENTIFIER'], "#{ENV['APP_IDENTIFIER']}.AnuNotificationServiceExtension"],
    type: 'appstore',
    username: ENV['APPLE_ID'],
    team_id: ENV['APPLE_TEAM_ID'],
    git_branch: ENV['CLIENT']
  )
  process_build(
    branch: options[:branch],
    installr: options[:installr],
    scheme: "#{ENV['CLIENT']} prod",
    output_name: ENV['PROD_NAME'],
    export_method: "app-store",
    profile: ENV["sigh_#{ENV['APP_IDENTIFIER']}_adhoc_profile-path"],
    profile_notification: ENV["sigh_#{ENV['APP_IDENTIFIER']}.AnuNotificationServiceExtension_adhoc_profile-path"]
  )
  upload_to_testflight(
    username: ENV['APPLE_ID'],
    app_identifier: ENV['APP_IDENTIFIER'],
    skip_waiting_for_build_processing: true,
  )
  sync_git(
    message: "chore: production build"
  )
end
